name: ci-golang

on: 
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3

      - name: Run Test
        run: go test --coverprofile=coverage.out

      - name: Run Application
        run: go run main.go